#!/usr/bin/env bash
set -euo pipefail

# Interactive helper to prepare a production .env for Roveltia.
# This script stays local: it does not connect to any remote host.
#
# It will:
# - create or update ./.env
# - build a SQL Server connection string
# - set Database__AutoMigrate
# - optionally set ROVELTIA_HOST_PORT
#
# Usage:
#   ./prepare-roveltia-production.sh

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${REPO_ROOT}/.env"
EXAMPLE_FILE="${REPO_ROOT}/.env.example"
BACKUP_FILE="${REPO_ROOT}/.env.bak"

prompt() {
  local label="$1"
  local default_value="${2:-}"
  local reply

  if [[ -n "${default_value}" ]]; then
    read -r -p "${label} [${default_value}]: " reply
    printf '%s' "${reply:-$default_value}"
  else
    read -r -p "${label}: " reply
    printf '%s' "${reply}"
  fi
}

prompt_secret() {
  local label="$1"
  local reply
  read -r -s -p "${label}: " reply
  printf '\n' >&2
  printf '%s' "${reply}"
}

prompt_yes_no() {
  local label="$1"
  local default_value="${2:-y}"
  local reply

  read -r -p "${label} [${default_value}]: " reply
  reply="${reply:-$default_value}"

  case "${reply,,}" in
    y|yes|true) printf 'true' ;;
    n|no|false) printf 'false' ;;
    *)
      echo "Please answer y or n." >&2
      exit 1
      ;;
  esac
}

echo "Preparing production .env for Roveltia"
echo

sql_host="$(prompt "SQL Server host" "roveltia.com")"
sql_port="$(prompt "SQL Server port" "1433")"
sql_database="$(prompt "Database name" "Roveltia")"
sql_user="$(prompt "SQL Server username")"
sql_password="$(prompt_secret "SQL Server password")"
trust_server_certificate="$(prompt_yes_no "Trust SQL Server certificate?" "y")"
auto_migrate="$(prompt_yes_no "Enable EF Core auto-migrate on startup?" "y")"
host_port="$(prompt "Published host port (leave blank for default 8081)" "")"

if [[ -f "${ENV_FILE}" ]]; then
  cp "${ENV_FILE}" "${BACKUP_FILE}"
  echo "Backed up existing .env to ${BACKUP_FILE}"
fi

if [[ "${trust_server_certificate}" == "true" ]]; then
  trust_value="true"
else
  trust_value="false"
fi

connection_string="Server=${sql_host},${sql_port};Database=${sql_database};User Id=${sql_user};Password=${sql_password};TrustServerCertificate=${trust_value}"

{
  echo "# Generated by prepare-roveltia-production.sh"
  echo "# Source template: ${EXAMPLE_FILE}"
  if [[ -n "${host_port}" ]]; then
    echo "ROVELTIA_HOST_PORT=${host_port}"
  else
    echo "# ROVELTIA_HOST_PORT=8081"
  fi
  echo "ConnectionStrings__DefaultConnection=${connection_string}"
  echo "Database__AutoMigrate=${auto_migrate}"
} > "${ENV_FILE}"

chmod 600 "${ENV_FILE}" || true

echo
echo "Wrote ${ENV_FILE}"
echo
echo "Next steps:"
echo "1. Review ${ENV_FILE}"
echo "2. Deploy with ./deploy-roveltia-safe.sh"
